version: 2.1

orbs:
 win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run: choco install innosetup -y
        name: Installing Inno Setup with Chocolatey

      - run: |
          cd ISCompiler
          ./ISCompil.exe
        name: Compiling Inno Setup script using ISCompil.exe