jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: BatchScript@1
    inputs:
      filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
      modifyEnvironment: true
    displayName: 'Enabling VS2019 Developer Command Prompt'

  - script: |
      cd ISCompiler
      cl.exe ISCompil.cpp
    displayName: 'Compiling ISCompil.cpp'

  - script: |
      cd ISCompiler
      ISCompil.exe
    displayName: 'Compiling Arduino Pro IDE using ISCompil.exe'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\Release\Arduino-Pro.IDE.Setup.exe'
      artifact: 'Arduino Pro IDE setup'
      publishLocation: 'pipeline'
    displayName: 'Publish Pipeline Artifacts'
