jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      cd ISCompiler
      ISCompil.exe
    displayName: 'Compiling Arduino Pro IDE using ISCompil.exe'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\Release\Arduino-Pro.IDE.Setup.exe'
      artifact: 'Arduino Pro IDE setup'
      publishLocation: 'pipeline'
    displayName: 'Publish Pipeline Artifacts'
